disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - force_unwrapping

opt_in_rules:
  - empty_count
  - explicit_init

line_length:
  warning: 120
  error: 200

excluded:
  - Carthage
  - Pods
  - fastlane
  - build 